[package]
name = "connman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bollard = "0.15.0"
env_logger = "0.10.0"
futures-util = "0.3.29"
log = "0.4.20"
tokio = { version = "1", features = ["full"] }
